version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm install
      - npm run test
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - node_modules/**/*
    - ./build/**/*
    - package.json
